### ISSUE TITLE
Issues need to be checked

### ISSUE THREAD

**Issue by hnngo** [votruongtrunghieu/fc5yJobTesting#4]
+ Thiếu gitignore để chặn node_modules, đừng push node_modules lên repo để giữ cho git history clean. Các dependencies thì được keep track thông qua `package.json` và `package-lock.json` rồi
> -  Read more: https://aptechbmt.edu.vn/hoc-lap-trinh/git-github/bai-6-gitignore-la-gi-su-dung-gitignore-sao-cho-hieu-qua-nhat-8.html

+ Em nên chia nhỏ thành các files thay vì bỏ hết tất cả vài cùng một file `App.tsx`. Ví dụ em có thể có `Item.tsx`, `Todo.tsx`, `User.tsx`. Việc em chia các file cũng sẽ dễ dàng hơn cho code splitting webpack sau này.
+ User và TodoList của em đang là một phần của App.tsx và em reference qua this.TodoList() và this.User() => nên tách ra thành 2 component như anh nói trên để dễ cho việc maintain (duy trì) và readability (đọc hiểu)
+ Do em để tất cả các component vào chung App.tsx thành ra em lại phải tạo 1 biến để reference đến App qua 
     `thisOfAppConstructor = this;` => không nên, ví dụ nếu với code em anh muốn reference đến TodoList thì sẽ phải hơi hacky một chút đúng không?
+ Hiện tại code của em mà muốn expand ra thêm nhiều component nữa thì file của em sẽ càng ngày càng bự ra tại cả TodoList và User của em đều dùng đến `thisOfAppConstructor` => lỗi coupling
+ Em dùng React nhưng anh thấy query khá nhiều từ `document.querySelector` hay select by id v.v.. => Nên hạn chế càng dùng ít càng tốt (nếu thật sự phải reference đến 1 dom nào đó thì nên dùng `React.useRef`)
+ Gợi ý của anh, tất cả các component nên hoạt động một cách độc lập và không nên quá phụ thuộc vào nhau, các components nên trao đổi với nhau qua props (vì đó là cách mà React Component nênhoạt động)

```
---App.tsx
|
---components
    |
    ---User.tsx
    |
    ---TodoList.tsx
```
+ Nếu được thì nên dùng hook version.

**Comment by ndkhaivn** [comment]
Should read (read DOM vs virtual DOM):
https://medium.com/velacorpblog/reactjs-và-các-khái-niệm-cơ-bản-7670380aa1e1
